name: dart_template
version: 1.0.0+3
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  json_serializable: ^6.6.1
  json_annotation: ^4.8.0
  aws_apigatewaymanagementapi_api: null
  aws_client: ^0.4.1
  aws_cognito_idp_api: null
  aws_common: null
  aws_lambda_dart_runtime:
  crypto: ^3.0.2
  dartx: ^1.1.0
  googleapis_auth: ^1.3.1
  #sentry: ^6.20.1
  shelf:
  shelf_router:
  nanoid: ^1.0.0
  s3_storage: ^1.0.4

dev_dependencies:
  build_runner: ^2.3.3
  lints:
